/// Multi-language support: English + Kannada
class AppStrings {
  static String _lang = 'en';

  static void setLanguage(String lang) => _lang = lang;
  static String get currentLanguage => _lang;

  static final _strings = <String, Map<String, String>>{
    'dashboard': {'en': 'Dashboard', 'kn': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್'},
    'new_bill': {'en': 'New Bill / Sales', 'kn': 'ಹೊಸ ಬಿಲ್ / ಮಾರಾಟ'},
    'purchase': {'en': 'Purchase', 'kn': 'ಖರೀದಿ'},
    'payments': {'en': 'Payments / History', 'kn': 'ಪಾವತಿಗಳು / ಇತಿಹಾಸ'},
    'items': {'en': 'Items', 'kn': 'ವಸ್ತುಗಳು'},
    'stock': {'en': 'Stock', 'kn': 'ದಾಸ್ತಾನು'},
    'customers': {'en': 'Customers', 'kn': 'ಗ್ರಾಹಕರು'},
    'suppliers': {'en': 'Suppliers', 'kn': 'ಪೂರೈಕೆದಾರರು'},
    'quotations': {'en': 'Quotations', 'kn': 'ಕೋಟೇಶನ್‌ಗಳು'},
    'expenses': {'en': 'Expenses', 'kn': 'ಖರ್ಚುಗಳು'},
    'recurring_bills': {'en': 'Recurring Bills', 'kn': 'ಮರುಕಳಿಸುವ ಬಿಲ್‌ಗಳು'},
    'credit_notes': {'en': 'Credit Notes', 'kn': 'ಕ್ರೆಡಿಟ್ ನೋಟ್‌ಗಳು'},
    'purchase_returns': {'en': 'Purchase Returns', 'kn': 'ಖರೀದಿ ಹಿಂತಿರುಗಿಸುವಿಕೆ'},
    'customer_ledger': {'en': 'Customer Ledger', 'kn': 'ಗ್ರಾಹಕ ಖಾತಾ ಪುಸ್ತಕ'},
    'reports': {'en': 'Reports', 'kn': 'ವರದಿಗಳು'},
    'settings': {'en': 'Settings', 'kn': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು'},
    'search': {'en': 'Search', 'kn': 'ಹುಡುಕಿ'},
    'add': {'en': 'Add', 'kn': 'ಸೇರಿಸಿ'},
    'save': {'en': 'Save', 'kn': 'ಉಳಿಸಿ'},
    'cancel': {'en': 'Cancel', 'kn': 'ರದ್ದುಮಾಡಿ'},
    'delete': {'en': 'Delete', 'kn': 'ಅಳಿಸಿ'},
    'edit': {'en': 'Edit', 'kn': 'ಸಂಪಾದಿಸಿ'},
    'total': {'en': 'Total', 'kn': 'ಒಟ್ಟು'},
    'subtotal': {'en': 'Subtotal', 'kn': 'ಉಪ ಮೊತ್ತ'},
    'tax': {'en': 'Tax', 'kn': 'ತೆರಿಗೆ'},
    'discount': {'en': 'Discount', 'kn': 'ರಿಯಾಯಿತಿ'},
    'paid': {'en': 'Paid', 'kn': 'ಪಾವತಿಸಲಾಗಿದೆ'},
    'unpaid': {'en': 'Unpaid', 'kn': 'ಪಾವತಿಯಾಗಿಲ್ಲ'},
    'balance_due': {'en': 'Balance Due', 'kn': 'ಬಾಕಿ ಮೊತ್ತ'},
    'invoice': {'en': 'Invoice', 'kn': 'ಸರಕುಪಟ್ಟಿ'},
    'quantity': {'en': 'Quantity', 'kn': 'ಪ್ರಮಾಣ'},
    'price': {'en': 'Price', 'kn': 'ಬೆಲೆ'},
    'name': {'en': 'Name', 'kn': 'ಹೆಸರು'},
    'phone': {'en': 'Phone', 'kn': 'ಫೋನ್'},
    'address': {'en': 'Address', 'kn': 'ವಿಳಾಸ'},
    'print': {'en': 'Print', 'kn': 'ಮುದ್ರಿಸಿ'},
    'share': {'en': 'Share', 'kn': 'ಹಂಚಿಕೊಳ್ಳಿ'},
    'export': {'en': 'Export', 'kn': 'ರಫ್ತು'},
    'today_sales': {'en': "Today's Sales", 'kn': 'ಇಂದಿನ ಮಾರಾಟ'},
    'monthly_sales': {'en': 'Monthly Sales', 'kn': 'ಮಾಸಿಕ ಮಾರಾಟ'},
    'outstanding': {'en': 'Outstanding', 'kn': 'ಬಾಕಿ'},
    'low_stock': {'en': 'Low Stock', 'kn': 'ಕಡಿಮೆ ದಾಸ್ತಾನು'},
    'sales_trend': {'en': '7-Day Sales Trend', 'kn': '7-ದಿನ ಮಾರಾಟ ಪ್ರವೃತ್ತಿ'},
    'top_items': {'en': 'Top Selling Items', 'kn': 'ಅತ್ಯಧಿಕ ಮಾರಾಟ ವಸ್ತುಗಳು'},
    'profit_loss': {'en': 'Profit & Loss', 'kn': 'ಲಾಭ ಮತ್ತು ನಷ್ಟ'},
    'gst_report': {'en': 'GST Report', 'kn': 'ಜಿಎಸ್‌ಟಿ ವರದಿ'},
    'sales_report': {'en': 'Sales Report', 'kn': 'ಮಾರಾಟ ವರದಿ'},
    'business_profile': {'en': 'Business Profile', 'kn': 'ವ್ಯಾಪಾರ ಪ್ರೊಫೈಲ್'},
    'staff': {'en': 'Staff / Multi-User', 'kn': 'ಸಿಬ್ಬಂದಿ / ಬಹು-ಬಳಕೆದಾರ'},
    'data_backup': {'en': 'Data Backup', 'kn': 'ಡೇಟಾ ಬ್ಯಾಕಪ್'},
    'language': {'en': 'Language', 'kn': 'ಭಾಷೆ'},
    'barcode_scan': {'en': 'Scan Barcode / HSN', 'kn': 'ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್ / HSN'},
    'no_results': {'en': 'No results found', 'kn': 'ಯಾವುದೇ ಫಲಿತಾಂಶ ಸಿಗಲಿಲ್ಲ'},
    'confirm_delete': {'en': 'Are you sure you want to delete?', 'kn': 'ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿದ್ದೀರಾ?'},
    'welcome': {'en': 'Welcome to My Billu', 'kn': 'ಮೈ ಬಿಲ್ಲೂಗೆ ಸ್ವಾಗತ'},
    'login': {'en': 'Login', 'kn': 'ಲಾಗಿನ್'},
    'username': {'en': 'Username', 'kn': 'ಬಳಕೆದಾರ ಹೆಸರು'},
    'password': {'en': 'Password', 'kn': 'ಪಾಸ್‌ವರ್ಡ್'},
    'generate_bill': {'en': 'Generate Bill', 'kn': 'ಬಿಲ್ ರಚಿಸಿ'},
    'collect_payment': {'en': 'Collect Payment', 'kn': 'ಪಾವತಿ ಸಂಗ್ರಹಿಸಿ'},
    'walk_in': {'en': 'Walk-in', 'kn': 'ನೇರ ಗ್ರಾಹಕ'},
    'cash': {'en': 'Cash', 'kn': 'ನಗದು'},
    'upi': {'en': 'UPI', 'kn': 'ಯುಪಿಐ'},
    'card': {'en': 'Card', 'kn': 'ಕಾರ್ಡ್'},
    'bank': {'en': 'Bank Transfer', 'kn': 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ'},
  };

  static String get(String key) => _strings[key]?[_lang] ?? _strings[key]?['en'] ?? key;
}


