import 'package:flutter/foundation.dart' show kIsWeb;
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../models/bill.dart';

enum InvoiceTemplate { modern, classic, minimal }
enum PaperSize { a4, a5 }

class InvoiceGenerator {

  static PdfPageFormat _getPageFormat(PaperSize size) {
    switch (size) {
      case PaperSize.a4: return PdfPageFormat.a4;
      case PaperSize.a5: return PdfPageFormat.a5;
    }
  }

  // ===== MAIN ENTRY POINTS =====

  static Future<void> generateAndPrint(
    Bill bill, {
    String businessName = 'My Billu',
    String businessAddress = '',
    String businessPhone = '',
    String businessGstin = '',
    InvoiceTemplate template = InvoiceTemplate.modern,
    PaperSize paperSize = PaperSize.a4,
  }) async {
    final bytes = await generatePdfBytes(bill,
      businessName: businessName, businessAddress: businessAddress,
      businessPhone: businessPhone, businessGstin: businessGstin,
      template: template, paperSize: paperSize);
    await Printing.layoutPdf(onLayout: (format) async => bytes);
  }

  static Future<Uint8List> generatePdfBytes(
    Bill bill, {
    String businessName = 'My Billu',
    String businessAddress = '',
    String businessPhone = '',
    String businessGstin = '',
    InvoiceTemplate template = InvoiceTemplate.modern,
    PaperSize paperSize = PaperSize.a4,
  }) async {
    final pdf = pw.Document();
    final pageFormat = _getPageFormat(paperSize);
    final isA5 = paperSize == PaperSize.a5;
    final margin = isA5 ? const pw.EdgeInsets.all(20) : const pw.EdgeInsets.all(32);

    pdf.addPage(pw.Page(
      pageFormat: pageFormat,
      margin: margin,
      build: (context) {
        switch (template) {
          case InvoiceTemplate.modern:
            return _buildModernTemplate(bill, businessName, businessAddress, businessPhone, businessGstin, isA5);
          case InvoiceTemplate.classic:
            return _buildClassicTemplate(bill, businessName, businessAddress, businessPhone, businessGstin, isA5);
          case InvoiceTemplate.minimal:
            return _buildMinimalTemplate(bill, businessName, businessAddress, businessPhone, businessGstin, isA5);
        }
      },
    ));
    return pdf.save();
  }

  static Future<void> shareInvoice(
    Bill bill, {
    String businessName = 'My Billu',
    String businessAddress = '',
    String businessPhone = '',
    String businessGstin = '',
    InvoiceTemplate template = InvoiceTemplate.modern,
    PaperSize paperSize = PaperSize.a4,
  }) async {
    final bytes = await generatePdfBytes(bill,
      businessName: businessName, businessAddress: businessAddress,
      businessPhone: businessPhone, businessGstin: businessGstin,
      template: template, paperSize: paperSize);

    if (kIsWeb) {
      await Printing.sharePdf(bytes: bytes, filename: 'Invoice_${bill.billNumber}.pdf');
    } else {
      final xFile = XFile.fromData(bytes, mimeType: 'application/pdf', name: 'Invoice_${bill.billNumber}.pdf');
      await Share.shareXFiles([xFile],
        text: 'Invoice ${bill.billNumber} - ${_cur(bill.totalAmount)} from $businessName');
    }
  }

  static Future<void> emailInvoice(
    Bill bill, {
    String? recipientEmail,
    String businessName = 'My Billu',
    String businessAddress = '',
    String businessPhone = '',
    String businessGstin = '',
    InvoiceTemplate template = InvoiceTemplate.modern,
    PaperSize paperSize = PaperSize.a4,
  }) async {
    final bytes = await generatePdfBytes(bill,
      businessName: businessName, businessAddress: businessAddress,
      businessPhone: businessPhone, businessGstin: businessGstin,
      template: template, paperSize: paperSize);

    final itemsList = bill.items.map((i) =>
      '  ${i.itemName} x${i.quantity} - ${_cur(i.total)}').join('\n');

    final subject = 'Invoice ${bill.billNumber} from $businessName - ${_cur(bill.totalAmount)}';
    final body = '''Dear ${bill.customerName ?? 'Customer'},

Please find below the invoice details:

Invoice No: ${bill.billNumber}
Date: ${_fmtDate(bill.createdAt)}

Items:
$itemsList

Subtotal: ${_cur(bill.subtotal)}
${bill.discount > 0 ? 'Discount: -${_cur(bill.discount)}\n' : ''}GST: ${_cur(bill.totalTax)}
Total: ${_cur(bill.totalAmount)}
${bill.paidAmount > 0 && bill.paidAmount < bill.totalAmount ? 'Paid: ${_cur(bill.paidAmount)}\nBalance Due: ${_cur(bill.balanceDue)}\n' : ''}
Thank you for your business!

$businessName
${businessPhone.isNotEmpty ? 'Phone: $businessPhone' : ''}
${businessGstin.isNotEmpty ? 'GSTIN: $businessGstin' : ''}

---
Generated by My Billu - Smart Billing Software''';

    final xFile = XFile.fromData(bytes, mimeType: 'application/pdf', name: 'Invoice_${bill.billNumber}.pdf');
    await Share.shareXFiles([xFile], subject: subject, text: body);
  }

  // ===== TEMPLATE 1: MODERN (Indigo accent, colored header) =====

  static pw.Widget _buildModernTemplate(Bill bill, String bName, String bAddr, String bPhone, String bGstin, bool isA5) {
    final fs = isA5 ? 0.8 : 1.0;
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      // Header with colored badge
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text(bName, style: pw.TextStyle(fontSize: 24 * fs, fontWeight: pw.FontWeight.bold)),
          if (bAddr.isNotEmpty) pw.Text(bAddr, style: pw.TextStyle(fontSize: 10 * fs, color: PdfColors.grey700)),
          if (bPhone.isNotEmpty) pw.Text('Phone: $bPhone', style: pw.TextStyle(fontSize: 10 * fs, color: PdfColors.grey700)),
          if (bGstin.isNotEmpty) pw.Text('GSTIN: $bGstin', style: pw.TextStyle(fontSize: 10 * fs, fontWeight: pw.FontWeight.bold)),
        ]),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Container(
            padding: pw.EdgeInsets.symmetric(horizontal: 16 * fs, vertical: 8 * fs),
            decoration: pw.BoxDecoration(color: PdfColors.indigo, borderRadius: pw.BorderRadius.circular(6)),
            child: pw.Text('TAX INVOICE', style: pw.TextStyle(fontSize: 14 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.white))),
          pw.SizedBox(height: 8),
          pw.Text('Invoice #: ${bill.billNumber}', style: pw.TextStyle(fontSize: 11 * fs, fontWeight: pw.FontWeight.bold)),
          pw.Text('Date: ${_fmtDate(bill.createdAt)}', style: pw.TextStyle(fontSize: 10 * fs, color: PdfColors.grey700)),
        ]),
      ]),
      pw.SizedBox(height: 16 * fs),
      pw.Divider(color: PdfColors.indigo200),
      pw.SizedBox(height: 10 * fs),
      // Customer
      pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Expanded(child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('Bill To:', style: pw.TextStyle(fontSize: 10 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.grey600)),
          pw.SizedBox(height: 4),
          pw.Text(bill.customerName ?? 'Walk-in Customer', style: pw.TextStyle(fontSize: 13 * fs, fontWeight: pw.FontWeight.bold)),
        ])),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text('Payment: ${bill.paymentMethod.name.toUpperCase()}', style: pw.TextStyle(fontSize: 10 * fs)),
          pw.Text('Status: ${bill.status.name.toUpperCase()}',
            style: pw.TextStyle(fontSize: 10 * fs, fontWeight: pw.FontWeight.bold,
              color: bill.status == BillStatus.paid ? PdfColors.green700 : PdfColors.red700)),
        ]),
      ]),
      pw.SizedBox(height: 14 * fs),
      // Items table
      _buildItemsTable(bill, PdfColors.indigo, PdfColors.white, fs),
      pw.SizedBox(height: 14 * fs),
      // Totals
      _buildTotalsBox(bill, PdfColors.grey100, PdfColors.grey300, PdfColors.indigo, fs),
      pw.SizedBox(height: 20 * fs),
      pw.Divider(color: PdfColors.grey300),
      pw.SizedBox(height: 6 * fs),
      pw.Center(child: pw.Text('Thank you for your business!', style: pw.TextStyle(fontSize: 11 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo))),
      pw.SizedBox(height: 3),
      pw.Center(child: pw.Text('Generated by My Billu - Smart Billing Software', style: pw.TextStyle(fontSize: 8 * fs, color: PdfColors.grey500))),
    ]);
  }

  // ===== TEMPLATE 2: CLASSIC (Professional, bordered, black & gold) =====

  static pw.Widget _buildClassicTemplate(Bill bill, String bName, String bAddr, String bPhone, String bGstin, bool isA5) {
    final fs = isA5 ? 0.8 : 1.0;
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      // Outer border effect header
      pw.Container(
        padding: pw.EdgeInsets.all(16 * fs),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: PdfColors.grey800, width: 2),
          borderRadius: pw.BorderRadius.circular(4)),
        child: pw.Column(children: [
          pw.Center(child: pw.Text(bName.toUpperCase(),
            style: pw.TextStyle(fontSize: 22 * fs, fontWeight: pw.FontWeight.bold, letterSpacing: 2))),
          if (bAddr.isNotEmpty) pw.Center(child: pw.Text(bAddr, style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey600))),
          pw.SizedBox(height: 4),
          pw.Row(mainAxisAlignment: pw.MainAxisAlignment.center, children: [
            if (bPhone.isNotEmpty) pw.Text('Tel: $bPhone  ', style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey600)),
            if (bGstin.isNotEmpty) pw.Text('GSTIN: $bGstin', style: pw.TextStyle(fontSize: 9 * fs, fontWeight: pw.FontWeight.bold)),
          ]),
          pw.Divider(color: PdfColors.grey800, thickness: 1.5),
          pw.SizedBox(height: 4),
          pw.Center(child: pw.Text('TAX INVOICE', style: pw.TextStyle(fontSize: 16 * fs, fontWeight: pw.FontWeight.bold, letterSpacing: 3))),
        ]),
      ),
      pw.SizedBox(height: 14 * fs),
      // Invoice details row
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('Invoice No: ${bill.billNumber}', style: pw.TextStyle(fontSize: 11 * fs, fontWeight: pw.FontWeight.bold)),
          pw.Text('Date: ${_fmtDate(bill.createdAt)}', style: pw.TextStyle(fontSize: 10 * fs)),
        ]),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text('Customer: ${bill.customerName ?? "Walk-in"}', style: pw.TextStyle(fontSize: 11 * fs, fontWeight: pw.FontWeight.bold)),
          pw.Text('Payment: ${bill.paymentMethod.name.toUpperCase()} | ${bill.status.name.toUpperCase()}', style: pw.TextStyle(fontSize: 10 * fs)),
        ]),
      ]),
      pw.SizedBox(height: 14 * fs),
      // Items
      _buildItemsTable(bill, PdfColors.grey800, PdfColors.white, fs),
      pw.SizedBox(height: 14 * fs),
      // Totals
      _buildTotalsBox(bill, PdfColors.amber50, PdfColors.amber200, PdfColors.grey800, fs),
      pw.SizedBox(height: 24 * fs),
      // Signature line
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Container(width: 150, child: pw.Divider(color: PdfColors.grey400)),
          pw.Text("Customer's Signature", style: pw.TextStyle(fontSize: 8 * fs, color: PdfColors.grey500)),
        ]),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Container(width: 150, child: pw.Divider(color: PdfColors.grey400)),
          pw.Text('Authorized Signature', style: pw.TextStyle(fontSize: 8 * fs, color: PdfColors.grey500)),
        ]),
      ]),
      pw.SizedBox(height: 12 * fs),
      pw.Center(child: pw.Text('Generated by My Billu', style: pw.TextStyle(fontSize: 7 * fs, color: PdfColors.grey400))),
    ]);
  }

  // ===== TEMPLATE 3: MINIMAL (Clean, lightweight, blue accent) =====

  static pw.Widget _buildMinimalTemplate(Bill bill, String bName, String bAddr, String bPhone, String bGstin, bool isA5) {
    final fs = isA5 ? 0.8 : 1.0;
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      // Simple clean header
      pw.Text(bName, style: pw.TextStyle(fontSize: 20 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
      if (bAddr.isNotEmpty) pw.Text(bAddr, style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey500)),
      pw.Row(children: [
        if (bPhone.isNotEmpty) pw.Text(bPhone, style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey500)),
        if (bPhone.isNotEmpty && bGstin.isNotEmpty) pw.Text('  |  ', style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey400)),
        if (bGstin.isNotEmpty) pw.Text('GSTIN: $bGstin', style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey500)),
      ]),
      pw.SizedBox(height: 6 * fs),
      pw.Container(height: 3, color: PdfColors.blue400),
      pw.SizedBox(height: 14 * fs),
      // Invoice meta + customer in 2 columns
      pw.Row(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Expanded(child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('INVOICE', style: pw.TextStyle(fontSize: 18 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.blue400, letterSpacing: 2)),
          pw.SizedBox(height: 6),
          _metaLine('Number', bill.billNumber, fs),
          _metaLine('Date', _fmtDate(bill.createdAt), fs),
          _metaLine('Status', bill.status.name.toUpperCase(), fs),
        ])),
        pw.Expanded(child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('BILL TO', style: pw.TextStyle(fontSize: 10 * fs, fontWeight: pw.FontWeight.bold, color: PdfColors.grey500, letterSpacing: 1)),
          pw.SizedBox(height: 6),
          pw.Text(bill.customerName ?? 'Walk-in Customer', style: pw.TextStyle(fontSize: 12 * fs, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text('Payment: ${bill.paymentMethod.name.toUpperCase()}', style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey500)),
        ])),
      ]),
      pw.SizedBox(height: 16 * fs),
      // Simple items table
      _buildItemsTable(bill, PdfColors.blue400, PdfColors.white, fs),
      pw.SizedBox(height: 14 * fs),
      // Right-aligned totals
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [
        pw.SizedBox(
          width: isA5 ? 180 : 220,
          child: pw.Column(children: [
            _simpleTotalRow('Subtotal', _cur(bill.subtotal), fs),
            _simpleTotalRow('CGST', _cur(bill.totalCgst), fs),
            _simpleTotalRow('SGST', _cur(bill.totalSgst), fs),
            pw.Container(height: 1, color: PdfColors.blue400, margin: pw.EdgeInsets.symmetric(vertical: 4 * fs)),
            _simpleTotalRow('Total', _cur(bill.totalAmount), fs, bold: true, color: PdfColors.blue800),
            if (bill.paidAmount > 0 && bill.paidAmount < bill.totalAmount) ...[
              _simpleTotalRow('Paid', _cur(bill.paidAmount), fs),
              _simpleTotalRow('Balance', _cur(bill.balanceDue), fs, bold: true, color: PdfColors.red700),
            ],
          ]),
        ),
      ]),
      pw.Spacer(),
      pw.Container(height: 1, color: PdfColors.grey200),
      pw.SizedBox(height: 6),
      pw.Center(child: pw.Text('Thank you! · My Billu', style: pw.TextStyle(fontSize: 8 * fs, color: PdfColors.grey400))),
    ]);
  }

  // ===== SHARED HELPERS =====

  static pw.Widget _buildItemsTable(Bill bill, PdfColor headerBg, PdfColor headerText, double fs) {
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontSize: 9 * fs, fontWeight: pw.FontWeight.bold, color: headerText),
      headerDecoration: pw.BoxDecoration(color: headerBg),
      headerAlignment: pw.Alignment.centerLeft,
      cellStyle: pw.TextStyle(fontSize: 9 * fs),
      cellHeight: 24 * fs,
      cellPadding: pw.EdgeInsets.symmetric(horizontal: 6 * fs, vertical: 3 * fs),
      columnWidths: {
        0: const pw.FlexColumnWidth(0.8),
        1: const pw.FlexColumnWidth(3),
        2: const pw.FlexColumnWidth(1.3),
        3: const pw.FlexColumnWidth(1),
        4: const pw.FlexColumnWidth(1),
        5: const pw.FlexColumnWidth(1),
        6: const pw.FlexColumnWidth(1.5),
      },
      headers: ['#', 'Item', 'Price', 'Qty', 'GST%', 'GST', 'Total'],
      data: bill.items.asMap().entries.map((e) => [
        '${e.key + 1}', e.value.itemName, _cur(e.value.unitPrice),
        '${e.value.quantity} ${e.value.unit}', '${e.value.taxRate}%',
        _cur(e.value.taxAmount), _cur(e.value.total),
      ]).toList(),
    );
  }

  static pw.Widget _buildTotalsBox(Bill bill, PdfColor bg, PdfColor border, PdfColor accent, double fs) {
    return pw.Row(mainAxisAlignment: pw.MainAxisAlignment.end, children: [
      pw.Container(
        width: 220 * fs, padding: pw.EdgeInsets.all(10 * fs),
        decoration: pw.BoxDecoration(color: bg, borderRadius: pw.BorderRadius.circular(6), border: pw.Border.all(color: border)),
        child: pw.Column(children: [
          _totalRow('Subtotal', _cur(bill.subtotal), fontSize: 10 * fs),
          pw.SizedBox(height: 3 * fs),
          _totalRow('CGST', _cur(bill.totalCgst), fontSize: 10 * fs),
          pw.SizedBox(height: 3 * fs),
          _totalRow('SGST', _cur(bill.totalSgst), fontSize: 10 * fs),
          pw.Divider(color: border),
          _totalRow('Total', _cur(bill.totalAmount), bold: true, fontSize: 13 * fs),
          if (bill.paidAmount > 0 && bill.paidAmount < bill.totalAmount) ...[
            pw.SizedBox(height: 3 * fs),
            _totalRow('Paid', _cur(bill.paidAmount), fontSize: 10 * fs),
            pw.SizedBox(height: 3 * fs),
            _totalRow('Balance Due', _cur(bill.balanceDue), bold: true, fontSize: 11 * fs, color: PdfColors.red700),
          ],
        ])),
    ]);
  }

  static pw.Widget _totalRow(String label, String value,
      {bool bold = false, double fontSize = 11, PdfColor? color}) {
    return pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
      pw.Text(label, style: pw.TextStyle(fontSize: fontSize, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
      pw.Text(value, style: pw.TextStyle(fontSize: fontSize, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, color: color)),
    ]);
  }

  static pw.Widget _simpleTotalRow(String label, String value, double fs, {bool bold = false, PdfColor? color}) {
    return pw.Padding(
      padding: pw.EdgeInsets.symmetric(vertical: 2 * fs),
      child: pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Text(label, style: pw.TextStyle(fontSize: 10 * fs, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, color: color)),
        pw.Text(value, style: pw.TextStyle(fontSize: 10 * fs, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal, color: color)),
      ]),
    );
  }

  static pw.Widget _metaLine(String label, String value, double fs) {
    return pw.Padding(
      padding: pw.EdgeInsets.only(bottom: 3 * fs),
      child: pw.Row(children: [
        pw.SizedBox(width: 60 * fs, child: pw.Text(label, style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey500))),
        pw.Text(': ', style: pw.TextStyle(fontSize: 9 * fs, color: PdfColors.grey400)),
        pw.Text(value, style: pw.TextStyle(fontSize: 10 * fs, fontWeight: pw.FontWeight.bold)),
      ]),
    );
  }

  static String _fmtDate(DateTime d) => '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';
  static String _cur(double a) => '\u20b9${a.toStringAsFixed(2)}';
}
